### ISSUE TITLE
How to get API key in entry.client.tsx ?

### ISSUE THREAD

**Issue by harshalpawshekar-greytip** [locize/locize-remix-i18next-example#2]
I was going through [this](https://locize.com/blog/remix-i18next/) article but cant figure out how to securely send API key 

We cant use `process.env` in `entry.client.tsx` 
Remix recommends that we use a loader function to send the secrets to front end but that is also not possible 
we can use localStorage to save API keys but that will not be secure

so is there any recommended way to securely get API key in `entry.client.tsx` ?

**Comment by adrai** [comment]
The problem is, as soon as the client needs the API-Key it is potentially exposed.
To restrict the api access you can additionally limit the api-key access by ip or referrer:
<img width="449" alt="image" src="https://github.com/locize/locize-remix-i18next-example/assets/1086194/ac0bf54a-62d5-4033-ae44-ec9b76763bc8">

**Comment by harshalpawshekar-greytip** [comment]
Ok thanks that will work
